name: Java CI

# Define when the workflow should run
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

# Define the jobs in the workflow
jobs:
  build:
    # Define the runner environment
    runs-on: ubuntu-latest

    # Define the steps to be taken in this job
    steps:
      # Checkout the repository code
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Java
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin' # Or any other preferred distribution
          java-version: '11' # Specify the Java version

      # Build the project with Maven
      - name: Build with Maven
        run: mvn clean install

      # Run tests with Maven
      - name: Test with Maven
        run: mvn test
